# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [49]:
import numpy as np
arr1d = np.arange(10)
print(arr1d)
arr2d = arr1d.reshape(2,5)
arr2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [47]:
arr1 = ([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2 = ([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
print(arr1)
print(arr2)
np.vstack((arr1,arr2))


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [46]:
arr1 = ([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2 = ([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
print(arr1)
print(arr2)
np.hstack((arr1,arr2))

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [45]:
arr2d = np.arange(10)
arr2d.resize(2,5)
print("Numpy array is:")
print(arr2d)
arr2d.flatten()

Numpy array is:
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [44]:
arr3d = np.arange(15)
arr3d.resize(3,5)
print("Numpy array in 2d is:")
print(arr3d)
np.ravel(arr3d)

Numpy array in 2d is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [42]:
arr1d = np.arange(15)
print("Numpy array in 1D is:")
print(arr1d)
arr2d = arr1d.reshape(5,3)
arr2d

Numpy array in 1D is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [40]:
arr1 =    np.arange(25).reshape(5,5) 
print("Numpy array is:")
print(arr1)
np.square(arr1)

Numpy array is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [39]:
arr1 = np.arange(30).reshape(5,6)
print("Numpy array is:")
print(arr1)
arr1.mean()

Numpy array is:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [24]:
arr1 = np.arange(30)
arr1.reshape(5,6)
arr1.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [28]:
arr1 = np.arange(30)
arr1.reshape(5,6)
np.median(arr1)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [33]:
arr1 = np.arange(30).reshape(5,6)
arr1
arr1.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [50]:
arr1 = np.arange(16).reshape(4,4)
print("Numpy array is:")
print(arr1)
trace = np.trace(arr1)
trace

Numpy array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [51]:
arr1 = np.arange(16).reshape(4,4)
print("Numpy array is:")
print(arr1)
np.linalg.det(arr1)


Numpy array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [52]:
x = np.arange(15)
p = np.percentile(x, 5)
print("The 5th percentile of an array is:")
print(p)
q = np. percentile(x,95)
print("The 95th percentile of an array is:")
print(q)

The 5th percentile of an array is:
0.7000000000000001
The 95th percentile of an array is:
13.299999999999999


## Question:15

### How to find if a given array has any null values?

In [53]:
np.isnan(x)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])